name: planthor-backend
services:
  api:
    build: .
    ports:
      - "5008:8080"
    env_file:
      - .env
    # depends_on:
    #   mongodb:
    #     condition: service_healthy
    networks:
      - planthor_network

  mongodb:
    image: mongo:8.2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Planthor_123
      MONGO_INITDB_DATABASE: planthordb
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - planthor_network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5
    command: start-dev --import-realm --http-port=8180
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: Planthor_123
      KC_DB: dev-mem
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8180"
    volumes:
      - ./infrastructure/keycloak/realms:/opt/keycloak/data/import:ro
    networks:
      - planthor_network

networks:
  planthor_network:
    driver: bridge
